### ISSUE TITLE
Could you please share the extraction code for the model.pth file

### ISSUE THREAD

**Issue by AnwesaBhattacharya** [leftthomas/DANet#2]
I am trying to run your repository, but it's missing the model.pth file. When I clicked on the link in the bottom of the page. it's asking for an extraction code

**Comment by leftthomas** [comment]
@AnwesaBhattacharya you should read `readme` carefully, the extraction code has been given.

**Comment by AnwesaBhattacharya** [comment]
Hello, thanks for responding!
I was trying to download the file using the extraction code, but looks like it needs the Baidu Netdisk client, which isn't working properly for me. Would it be possible to share the file through a google drive link?

**Comment by leftthomas** [comment]
@AnwesaBhattacharya I have no space in Google drive, if you could not access Baidu Netdisk, you could train the model by yourself.
