### ISSUE TITLE
Detectron2 error

### ISSUE THREAD

**Issue by Shruti-Bansal** [leftthomas/DANet#4]
Hi,

Thank you for your clear and understandable repo.

I followed your instructions to install detectron2, however, it would not install with the  @master so I installed it without the @master as below:
pip install git+https://github.com/facebookresearch/detectron2.git

Now it is giving me this error when I run training:
   
from detectron2.evaluation import (
ImportError: cannot import name 'CityscapesEvaluator' from 'detectron2.evaluation'

Any suggestions would be really helpful.

**Comment by leftthomas** [comment]
@Shruti-Bansal you should install old version detectron2, or to modify the related code according error message following detectron2 docs.
