### ISSUE TITLE
Evaluator not working

### ISSUE THREAD

**Issue by Shruti-Bansal** [leftthomas/DANet#5]
Thanks for your response earlier. I am able to train, however, the evaluator is not being found.

WARNING [04/16 08:32:32 d2.engine.defaults]: No evaluator found. Use `DefaultTrainer.test(evaluators=)`, or implement its `build_evaluator` method.

Any advice?
If I go to an old version of Detectron, which one should that be?

**Comment by leftthomas** [comment]
@Shruti-Bansal you could refer Detectron2 docs to find the solution or to install the old Detectron2 according the commit time with this repo.
