### ISSUE TITLE
Output Images

### ISSUE THREAD

**Issue by Shruti-Bansal** [leftthomas/DANet#6]
Thank you for your guidance.

I want to visualize the output results and run the network on test images as well , but could not find any code in the repo. Could you help ?  Are the validation images written somewhere after segmentation?

**Comment by leftthomas** [comment]
@Shruti-Bansal you should  read the docs of `detectron2` to learn how to vis the results, it has tell, not always ask other to tell you how to do, and not open new issues, you could comment on the old issues.
